sudo: true

matrix:
  include:
    - env: PLATFORM=x86_64 UNICODE=  CMAKE= WINE_PACKAGE=winehq-stable:amd64
      addons:
        apt:
          packages:
            - binutils-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
            - g++-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
    - env: PLATFORM=i686   UNICODE=  CMAKE= WINE_PACKAGE=winehq-stable:i386
      addons:
        apt:
          packages:
            - binutils-mingw-w64-i686
            - mingw-w64-i686-dev
            - g++-mingw-w64-i686
            - gcc-mingw-w64-i686
    - env: PLATFORM=x86_64 UNICODE=1 CMAKE= WINE_PACKAGE=winehq-stable:amd64
      addons:
        apt:
          packages:
            - binutils-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
            - g++-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
    - env: PLATFORM=i686   UNICODE=1 CMAKE= WINE_PACKAGE=winehq-stable:i386
      addons:
        apt:
          packages:
            - binutils-mingw-w64-i686
            - mingw-w64-i686-dev
            - g++-mingw-w64-i686
            - gcc-mingw-w64-i686
    - env: PLATFORM=x86_64 UNICODE=  CMAKE=1 WINE_PACKAGE=winehq-stable:amd64
      addons:
        apt:
          packages:
            - binutils-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
            - g++-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
    - env: PLATFORM=i686   UNICODE=  CMAKE=1 WINE_PACKAGE=winehq-stable:i386
      addons:
        apt:
          packages:
            - binutils-mingw-w64-i686
            - cmake
            - mingw-w64-i686-dev
            - g++-mingw-w64-i686
            - gcc-mingw-w64-i686
    - env: PLATFORM=x86_64 UNICODE=1 CMAKE=1 WINE_PACKAGE=winehq-stable:amd64
      addons:
        apt:
          packages:
            - binutils-mingw-w64-x86-64
            - cmake
            - mingw-w64-x86-64-dev
            - g++-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
    - env: PLATFORM=i686   UNICODE=1 CMAKE=1 WINE_PACKAGE=winehq-stable:i386
      addons:
        apt:
          packages:
            - binutils-mingw-w64-i686
            - cmake
            - mingw-w64-i686-dev
            - g++-mingw-w64-i686
            - gcc-mingw-w64-i686

language: cpp

dist: xenial

cache:
  - apt
  - ccache

before_script:
  - curl https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
  - echo "deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main" | sudo tee /etc/apt/sources.list.d/winehq.list
  - sudo apt-get -y update && sudo apt-get -y install --install-recommends $WINE_PACKAGE
  - if [ ! -z "$CMAKE" ]; then cmake -DPLATFORM=$PLATFORM -DUNICODE=$UNICODE -DTESTSUITE=ON -H. -B.; fi

script:
  - if [ -z "$CMAKE" ]; then make PLATFORM=$PLATFORM UNICODE=$UNICODE; fi
  - if [ -z "$CMAKE" ]; then make test PLATFORM=$PLATFORM UNICODE=$UNICODE; fi
  - if [ ! -z "$CMAKE" ]; then cmake --build .; fi
  - cd example/DllLoader
  - ../../tests/runwine.sh $PLATFORM ./DllLoader.exe
  - ../../tests/runwine.sh $PLATFORM ./DllLoaderLoader.exe
  - cd ../../tests
  - ./runwine.sh $PLATFORM ./TestSuite.exe
